name: "ci-cd pipeline"

on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install 
    // - name: Run tests
    // - run: npm test
    - name: Build file
      run: npm run build
      

    // deploy the application to netlify
    - name: cpbudgetfriendly
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: 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
        netlify-auth-token: 9LG-JEwMuBk6EzSIji0YUvCQQ7EqiyuSanCWCDRK6zk
        netlify-site-id: 640fd8cb-16af-4a65-9f80-d406dfabcce7
        build-dir: './build'
        comment-on-commit: true